/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useAppSelector } from '@src/hooks/redux'
import { MaterialState } from '@src/module/features/3d/threeDSlice'

type GLTFResult = GLTF & {
  nodes: {
    円柱002: THREE.SkinnedMesh
    円柱002_1: THREE.SkinnedMesh
    Master: THREE.Bone
    neutral_bone: THREE.Bone
  }
  materials: {
    マテリアル: THREE.MeshStandardMaterial
    ['マテリアル.002']: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Action'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

interface Props {
  material: MaterialState
}

export const Model: React.VFC<Props> = ({ material }) => {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF(
    '/3dModels/turtle.glb'
  ) as GLTFResult
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Action !== null ? actions.Action.play() : null
  })

  const selectedMaterial = new THREE.MeshStandardMaterial({
    color: material.hexColor,
    roughness: material.roughness,
    metalness: material.matelness,
    opacity: material.alpha,
    transparent: true,
  })

  return (
    <group ref={group as any} dispose={null}>
      <group name="Scene">
        <group name="アーマチュア001">
          <primitive object={nodes.Master} />
          <primitive object={nodes.neutral_bone} />
          <group name="Turtle">
            <skinnedMesh
              name="円柱002"
              geometry={nodes.円柱002.geometry}
              material={
                material.initialize ? materials.マテリアル : selectedMaterial
              }
              skeleton={nodes.円柱002.skeleton}
            />
            <skinnedMesh
              name="円柱002_1"
              geometry={nodes.円柱002_1.geometry}
              material={materials['マテリアル.002']}
              skeleton={nodes.円柱002_1.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3dModels/turtle.glb')
